// Generated by CoffeeScript 1.7.1
'use strict';
module.exports = function(grunt) {
  grunt.initConfig({
    browserify: {
      dist: {
        files: {
          'dist/bundle.js': ['src/index.js']
        }
      }
    },
    exec: {
      clean: {
        command: 'rm -rf dist'
      },
      mv4test: {
        command: 'cp dist/bundle.js tt/'
      }
    },
    connect: {
      server: {
        options: {
          base: ["tt"],
          hostname: "0.0.0.0"
        }
      },
      options: {
        port: 8000,
        livereload: 35729
      }
    },
    watch: {
      livereload: {
        files: ["src/**/*.js", "tt/index.html"],
        tasks: ["browserify", "exec:mv4test"],
        options: {
          livereload: 35729
        }
      }
    }
  });

  grunt.loadNpmTasks('grunt-browserify');
  grunt.loadNpmTasks('grunt-exec');
  grunt.loadNpmTasks("grunt-contrib-connect");
  grunt.loadNpmTasks("grunt-contrib-watch");

  grunt.registerTask('default', [
    'browserify',
    'exec:mv4test',
    "connect", 
    "watch"
  ]);
  grunt.registerTask('build', [
    'browserify',
    //todo
  ]);
};
